### ISSUE TITLE
Third Platform Construction

### ISSUE THREAD

**Issue by TheElectricDream** [Carleton-SRCL/SPOT#10]
The software theoretically works with a third platform (BLUE), but this platform has not been built. All the hardware is in the lab, it's a matter of someone building it.

**Comment by Carleton-SRCL** [comment]
Courtney Bashnick and Nolan Chafe were put in charge of this task, which is set to begin in January 2022.

**Comment by TheElectricDream** [comment]
The platform has been built and tested in the lab! Well done team!
