### ISSUE TITLE
Robotic Arm LEDs Connectors Need Labels

### ISSUE THREAD

**Issue by TheElectricDream** [Carleton-SRCL/SPOT#18]
The LED female-male connectors do not have any labels on the ports. Right now, connecting them is trial and error. Someone should label them.

**Comment by Carleton-SRCL** [comment]
Parker should look into it this summer.

**Comment by Kirkados** [comment]
TBD on whether this is needed anymore, as the arm joint encoders can now be read in real-time

**Comment by TheElectricDream** [comment]
When I read the encoder values in the lab there are a ton of data drops in the encoder data. Was that what you experienced?
