### ISSUE TITLE
Air Compressor Won't Fully Charge Tanks

### ISSUE THREAD

**Issue by TheElectricDream** [Carleton-SRCL/SPOT#21]
Significant leak present in air compressor. Prevents charging beyond 2500 PSI.

**Comment by Carleton-SRCL** [comment]
On Oct. 1st, Paul Howard from Ottawa Compressor Services (OCS) confirmed that the missing parts required for the annual maintenance (including the replacement of the faulty valve) were ordered and should arrive sometime next week.

**Comment by Carleton-SRCL** [comment]
Leak is fixed and compressor got its annual maintenance.
