### ISSUE TITLE
"Run Simulation" error on first attempt

### ISSUE THREAD

**Issue by c-bash** [Carleton-SRCL/SPOT#30]
**In the laboratory:** 
When the RP3s are powered on and the "Run Simulation" button is clicked for the first time in the GUI on the lab computer, MATLAB will try to update libraries on one of the Pis. It will fail out, as per the error messages below.

![runsimulation-spot3p8p0-debug-1](https://user-images.githubusercontent.com/89787972/175078027-f09bbf39-6413-4305-9d99-c47904a13ced.png)

![runsimulation-spot3p8p0-debug-2](https://user-images.githubusercontent.com/89787972/175078073-f9619396-06be-448b-9ca3-30105d107cc4.png)

Clicking "Run Simulation" a second time will be successful.

**At home:**
When working at home on a personal computer, the MATLAB tries to connect to the Pis upon clicking "Run Simulation" for the first time. It will throw the error as seen below.

![image](https://user-images.githubusercontent.com/89787972/175180596-f7eb8d7d-30a2-4ecb-830c-c1d421e127a4.png)

**Comment by TheElectricDream** [comment]
Fixed in the latest release.
