### ISSUE TITLE
Angle wrapping in simulation versus experiment

### ISSUE THREAD

**Issue by c-bash** [Carleton-SRCL/SPOT#32]
**Problem:**
In simulation, the angular positions of the platforms (e.g., RED_Rz, BLACK_Rz, BLUE_Rz) are not wrapped.
In experiment, the angular positions of the platforms _are_ wrapped (due to PhaseSpace). The wrap is from -pi to pi, or vice versa.

**Proposed Solution:**
Simulation output should be changed to match experiment output.

**Comment by TheElectricDream** [comment]
Finally closing this with the pre-release of SPOT 4.0.
