### ISSUE TITLE
All Platforms Need Proper PID Tuning 

### ISSUE THREAD

**Issue by TheElectricDream** [Carleton-SRCL/SPOT#38]
Proper PID tuning would help with overshoot.

**Comment by Carleton-SRCL** [comment]
This can be done very easily and effectively using Ziegler-Nichols empirical tuning rule #2

**Comment by TheElectricDream** [comment]
Yep, it's on my list to do. I will say that looking back at old software I actually did do this... but if I recall correctly, I cranked the damping gain higher then what the rules indicated because the 'proper' tuning uses a lot more air. The higher damping results in a lot less air being used when the platform tries to sit still.

I'll investigate anyways and see if anything has changed.

**Comment by TheElectricDream** [comment]
Finally closing this with the pre-release of SPOT 4.0.
