### ISSUE TITLE
Rewire RED Thrusters

### ISSUE THREAD

**Issue by TheElectricDream** [Carleton-SRCL/SPOT#39]
The thruster order on RED should match the other platforms.

**Comment by TheElectricDream** [comment]
Done! Unfortunately the colors do not match the other platforms but at least the GPIO layout now matches (so GPIO 10 is thruster 5 on all platforms even though the color of the wire does not match).

![image](https://user-images.githubusercontent.com/68435427/224549907-1bb5cfa6-41a1-408d-9ccd-18e7fd780e95.png)

**Comment by c-bash** [comment]
Rewired so all platform thrusters have the same 'number-colour' coding. See [electrical diagram](https://github.com/Carleton-SRCL/SPOT/wiki/Power-Subsystem) for wiring details.
