### ISSUE TITLE
Barrier around table needed

### ISSUE THREAD

**Issue by Carleton-SRCL** [Carleton-SRCL/SPOT#41]

**Comment by TheElectricDream** [comment]
If you find a student to do this, I have some ideas that I have been carrying in my brain since I originally brought this up in 2017. Obviously it's not worth me spending contract time on actually building this, but I have some guidance/requirements to provide.

**Comment by Carleton-SRCL** [comment]
I think I'll save this one for the capstone this fall. I have some ideas as well, so let's brainstorm later this year.

**Comment by natashadawnn** [comment]
Done finally!
