### ISSUE TITLE
Create a comprehensive Wiki section on Computer Vision

### ISSUE THREAD

**Issue by Carleton-SRCL** [Carleton-SRCL/SPOT#45]
User guide type of section on Wiki that explains, in a step-by-step approach, how to develop, implement, interface with sensors, test, and deploy in experiments basic computer vision software.

**Comment by TheElectricDream** [comment]
I am fairly confident that this is complete, or at least most of the way there, thanks to @NerdAlert57. Going to close this for now.

https://github.com/Carleton-SRCL/SPOT/wiki/Getting-Started-with-Computer-Vision
