### ISSUE TITLE
Upgrade platform stands

### ISSUE THREAD

**Issue by c-bash** [Carleton-SRCL/SPOT#48]
Upgrade to the "wooden blocks" that the platforms sit on. It is not too easy to place the platforms on the blocks correctly without crushing the plumbing to the pucks. Also, sometimes the platform rotates on the block (not with it) and so the plumbing gets squished.

**Comment by natashadawnn** [comment]
The new stands still need some modifications, which I will be working on this month, but the stands have been upgraded
