### ISSUE TITLE
Upgrade Drain Tubes on Air Compressor

### ISSUE THREAD

**Issue by c-bash** [Carleton-SRCL/SPOT#52]
Air compressor: Current drain tubes for points B and C are cracking and quite short with liquid currently being collected by a plastic water bottle. 

An upgrade is required such that the drain tubes are replaced and, ideally, not pointing directly at the platforms. A more semi-permanent collection basin should be at the end of the tubes.

**Comment by Kirkados** [comment]
Perhaps an elbow could run drain tubes down towards the floor where an absorbent material (like a dog pee pad?) absorbs the ejected moisture.

**Comment by TheElectricDream** [comment]
A pro tip as well, I've stopped using the bottle and I use a bundle of shop towels to catch the liquid. Just less gross that way.

**Comment by c-bash** [comment]
This has been completed! In future, we likely want to move the drain box to a better location since currently it blocks the bottom right drawer. 

![IMG_4292 17060](https://github.com/Carleton-SRCL/SPOT/assets/89787972/3297a6b6-9f33-417d-9535-a42f0de10c7e)
