### ISSUE TITLE
SPOT GUI Indicates (0,0,0) for Platforms Positions, but LEDs Stay On

### ISSUE THREAD

**Issue by TheElectricDream** [Carleton-SRCL/SPOT#56]
I believe the issue is caused by the PhaseSpace program that sends the data crashing in the background. This would result in the LEDs being on (PhaseSpace initialized), but there is no UDP to send the data, and the GUI is stuck in a pseudo-functional state. I can add a check in the GUI to record the ID of the PhaseSpace executable when it is started, and then I can check that it is still running every couple of seconds. If it crashed, I can toggle the GUI PhaseSpace switch to OFF to properly shut down the PhaseSpace cameras and then I can provide a warning to the user to simply "try again".

**Comment by TheElectricDream** [comment]
The current workaround is to restart the ground station computer.

**Comment by c-bash** [comment]
Another potential fix is to replace the StreamData.exe file in your current project to the most up-to-date version [found on the wiki](https://github.com/Carleton-SRCL/SPOT/blob/main/Template_Files/Resources/StreamData.exe)

**Comment by TheElectricDream** [comment]
Resolved in [4.1](https://github.com/Carleton-SRCL/SPOT/releases/tag/4.1.0-prerelease.1)
