### ISSUE TITLE
Add Orientation Labels to the Platform Tops

### ISSUE THREAD

**Issue by TheElectricDream** [Carleton-SRCL/SPOT#65]
Add a label to the inside of platform tops (that have the LED) to indicate the correct orientation. Open to other ideas.

**Comment by c-bash** [comment]
Spoke with Steve, and we think that the best way forward is to have the orientation engraved on the platform tops. Perhaps something like "Control Panel This Way" on the side with the control panel. Would it also be beneficial for students/researchers to engrave the +X and +Y directions of the body frame on the platform tops?

**Comment by TheElectricDream** [comment]
That would certainly look more professional, I'm all for it
